// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ezbiz

import (
	"github.com/99designs/gqlgen/graphql"
)

type File struct {
	Name    string `json:"name"`
	Size    int    `json:"size"`
	Content string `json:"content"`
}

type UploadFile struct {
	ID   int            `json:"id"`
	File graphql.Upload `json:"file"`
}
