// Code generated by ent, DO NOT EDIT.

package question

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"ezbiz.com/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldTitle, v))
}

// Required applies equality check predicate on the "required" field. It's identical to RequiredEQ.
func Required(v bool) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldRequired, v))
}

// ExtraData applies equality check predicate on the "extra_data" field. It's identical to ExtraDataEQ.
func ExtraData(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldExtraData, v))
}

// Rule applies equality check predicate on the "rule" field. It's identical to RuleEQ.
func Rule(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldRule, v))
}

// Dependencies applies equality check predicate on the "dependencies" field. It's identical to DependenciesEQ.
func Dependencies(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldDependencies, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldCreatedBy, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Question {
	return predicate.Question(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Question {
	return predicate.Question(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Question {
	return predicate.Question(sql.FieldContainsFold(FieldLabel, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Question {
	return predicate.Question(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Question {
	return predicate.Question(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Question {
	return predicate.Question(sql.FieldContainsFold(FieldTitle, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldType, vs...))
}

// RequiredEQ applies the EQ predicate on the "required" field.
func RequiredEQ(v bool) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldRequired, v))
}

// RequiredNEQ applies the NEQ predicate on the "required" field.
func RequiredNEQ(v bool) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldRequired, v))
}

// ExtraDataEQ applies the EQ predicate on the "extra_data" field.
func ExtraDataEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldExtraData, v))
}

// ExtraDataNEQ applies the NEQ predicate on the "extra_data" field.
func ExtraDataNEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldExtraData, v))
}

// ExtraDataIn applies the In predicate on the "extra_data" field.
func ExtraDataIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldExtraData, vs...))
}

// ExtraDataNotIn applies the NotIn predicate on the "extra_data" field.
func ExtraDataNotIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldExtraData, vs...))
}

// ExtraDataGT applies the GT predicate on the "extra_data" field.
func ExtraDataGT(v string) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldExtraData, v))
}

// ExtraDataGTE applies the GTE predicate on the "extra_data" field.
func ExtraDataGTE(v string) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldExtraData, v))
}

// ExtraDataLT applies the LT predicate on the "extra_data" field.
func ExtraDataLT(v string) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldExtraData, v))
}

// ExtraDataLTE applies the LTE predicate on the "extra_data" field.
func ExtraDataLTE(v string) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldExtraData, v))
}

// ExtraDataContains applies the Contains predicate on the "extra_data" field.
func ExtraDataContains(v string) predicate.Question {
	return predicate.Question(sql.FieldContains(FieldExtraData, v))
}

// ExtraDataHasPrefix applies the HasPrefix predicate on the "extra_data" field.
func ExtraDataHasPrefix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasPrefix(FieldExtraData, v))
}

// ExtraDataHasSuffix applies the HasSuffix predicate on the "extra_data" field.
func ExtraDataHasSuffix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasSuffix(FieldExtraData, v))
}

// ExtraDataEqualFold applies the EqualFold predicate on the "extra_data" field.
func ExtraDataEqualFold(v string) predicate.Question {
	return predicate.Question(sql.FieldEqualFold(FieldExtraData, v))
}

// ExtraDataContainsFold applies the ContainsFold predicate on the "extra_data" field.
func ExtraDataContainsFold(v string) predicate.Question {
	return predicate.Question(sql.FieldContainsFold(FieldExtraData, v))
}

// RuleEQ applies the EQ predicate on the "rule" field.
func RuleEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldRule, v))
}

// RuleNEQ applies the NEQ predicate on the "rule" field.
func RuleNEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldRule, v))
}

// RuleIn applies the In predicate on the "rule" field.
func RuleIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldRule, vs...))
}

// RuleNotIn applies the NotIn predicate on the "rule" field.
func RuleNotIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldRule, vs...))
}

// RuleGT applies the GT predicate on the "rule" field.
func RuleGT(v string) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldRule, v))
}

// RuleGTE applies the GTE predicate on the "rule" field.
func RuleGTE(v string) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldRule, v))
}

// RuleLT applies the LT predicate on the "rule" field.
func RuleLT(v string) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldRule, v))
}

// RuleLTE applies the LTE predicate on the "rule" field.
func RuleLTE(v string) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldRule, v))
}

// RuleContains applies the Contains predicate on the "rule" field.
func RuleContains(v string) predicate.Question {
	return predicate.Question(sql.FieldContains(FieldRule, v))
}

// RuleHasPrefix applies the HasPrefix predicate on the "rule" field.
func RuleHasPrefix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasPrefix(FieldRule, v))
}

// RuleHasSuffix applies the HasSuffix predicate on the "rule" field.
func RuleHasSuffix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasSuffix(FieldRule, v))
}

// RuleEqualFold applies the EqualFold predicate on the "rule" field.
func RuleEqualFold(v string) predicate.Question {
	return predicate.Question(sql.FieldEqualFold(FieldRule, v))
}

// RuleContainsFold applies the ContainsFold predicate on the "rule" field.
func RuleContainsFold(v string) predicate.Question {
	return predicate.Question(sql.FieldContainsFold(FieldRule, v))
}

// DependenciesEQ applies the EQ predicate on the "dependencies" field.
func DependenciesEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldDependencies, v))
}

// DependenciesNEQ applies the NEQ predicate on the "dependencies" field.
func DependenciesNEQ(v string) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldDependencies, v))
}

// DependenciesIn applies the In predicate on the "dependencies" field.
func DependenciesIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldDependencies, vs...))
}

// DependenciesNotIn applies the NotIn predicate on the "dependencies" field.
func DependenciesNotIn(vs ...string) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldDependencies, vs...))
}

// DependenciesGT applies the GT predicate on the "dependencies" field.
func DependenciesGT(v string) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldDependencies, v))
}

// DependenciesGTE applies the GTE predicate on the "dependencies" field.
func DependenciesGTE(v string) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldDependencies, v))
}

// DependenciesLT applies the LT predicate on the "dependencies" field.
func DependenciesLT(v string) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldDependencies, v))
}

// DependenciesLTE applies the LTE predicate on the "dependencies" field.
func DependenciesLTE(v string) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldDependencies, v))
}

// DependenciesContains applies the Contains predicate on the "dependencies" field.
func DependenciesContains(v string) predicate.Question {
	return predicate.Question(sql.FieldContains(FieldDependencies, v))
}

// DependenciesHasPrefix applies the HasPrefix predicate on the "dependencies" field.
func DependenciesHasPrefix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasPrefix(FieldDependencies, v))
}

// DependenciesHasSuffix applies the HasSuffix predicate on the "dependencies" field.
func DependenciesHasSuffix(v string) predicate.Question {
	return predicate.Question(sql.FieldHasSuffix(FieldDependencies, v))
}

// DependenciesEqualFold applies the EqualFold predicate on the "dependencies" field.
func DependenciesEqualFold(v string) predicate.Question {
	return predicate.Question(sql.FieldEqualFold(FieldDependencies, v))
}

// DependenciesContainsFold applies the ContainsFold predicate on the "dependencies" field.
func DependenciesContainsFold(v string) predicate.Question {
	return predicate.Question(sql.FieldContainsFold(FieldDependencies, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int) predicate.Question {
	return predicate.Question(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int) predicate.Question {
	return predicate.Question(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int) predicate.Question {
	return predicate.Question(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int) predicate.Question {
	return predicate.Question(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int) predicate.Question {
	return predicate.Question(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int) predicate.Question {
	return predicate.Question(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int) predicate.Question {
	return predicate.Question(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int) predicate.Question {
	return predicate.Question(sql.FieldLTE(FieldCreatedBy, v))
}

// HasFromQuestionGroup applies the HasEdge predicate on the "from_question_group" edge.
func HasFromQuestionGroup() predicate.Question {
	return predicate.Question(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FromQuestionGroupTable, FromQuestionGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromQuestionGroupWith applies the HasEdge predicate on the "from_question_group" edge with a given conditions (other predicates).
func HasFromQuestionGroupWith(preds ...predicate.QuestionGroup) predicate.Question {
	return predicate.Question(func(s *sql.Selector) {
		step := newFromQuestionGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuestionResponse applies the HasEdge predicate on the "question_response" edge.
func HasQuestionResponse() predicate.Question {
	return predicate.Question(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, QuestionResponseTable, QuestionResponseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionResponseWith applies the HasEdge predicate on the "question_response" edge with a given conditions (other predicates).
func HasQuestionResponseWith(preds ...predicate.QuestionResponse) predicate.Question {
	return predicate.Question(func(s *sql.Selector) {
		step := newQuestionResponseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Question) predicate.Question {
	return predicate.Question(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Question) predicate.Question {
	return predicate.Question(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Question) predicate.Question {
	return predicate.Question(sql.NotPredicates(p))
}
