"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KW_LET = exports.RBRACE = exports.LBRACE = exports.RPAREN = exports.LPAREN = exports.SEMICOLON = exports.COMMA = exports.GREATER_THAN_EQUAL = exports.GREATER_THAN = exports.LESS_THAN_EQUAL = exports.LESS_THAN = exports.SLASH = exports.ASTERISK = exports.MINUS = exports.PLUS = exports.ASSIGN = exports.INT = exports.ID = exports.EOF = exports.ILLEGAL = void 0;
exports.ILLEGAL = "illegal";
exports.EOF = "eof";
exports.ID = "id";
exports.INT = "int";
exports.ASSIGN = "=";
exports.PLUS = "+";
exports.MINUS = "-";
exports.ASTERISK = "*";
exports.SLASH = "/";
exports.LESS_THAN = "<";
exports.LESS_THAN_EQUAL = "<=";
exports.GREATER_THAN = ">";
exports.GREATER_THAN_EQUAL = ">=";
exports.COMMA = ",";
exports.SEMICOLON = ";";
exports.LPAREN = "(";
exports.RPAREN = ")";
exports.LBRACE = "{";
exports.RBRACE = "}";
exports.KW_LET = "let";
