// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"ezbiz.com/ent/entform"
	"ezbiz.com/ent/entformquestion"
	"ezbiz.com/ent/predicate"
)

// EntFormQuestionQuery is the builder for querying EntFormQuestion entities.
type EntFormQuestionQuery struct {
	config
	ctx        *QueryContext
	order      []entformquestion.OrderOption
	inters     []Interceptor
	predicates []predicate.EntFormQuestion
	withForm   *EntFormQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EntFormQuestion) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntFormQuestionQuery builder.
func (efqq *EntFormQuestionQuery) Where(ps ...predicate.EntFormQuestion) *EntFormQuestionQuery {
	efqq.predicates = append(efqq.predicates, ps...)
	return efqq
}

// Limit the number of records to be returned by this query.
func (efqq *EntFormQuestionQuery) Limit(limit int) *EntFormQuestionQuery {
	efqq.ctx.Limit = &limit
	return efqq
}

// Offset to start from.
func (efqq *EntFormQuestionQuery) Offset(offset int) *EntFormQuestionQuery {
	efqq.ctx.Offset = &offset
	return efqq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (efqq *EntFormQuestionQuery) Unique(unique bool) *EntFormQuestionQuery {
	efqq.ctx.Unique = &unique
	return efqq
}

// Order specifies how the records should be ordered.
func (efqq *EntFormQuestionQuery) Order(o ...entformquestion.OrderOption) *EntFormQuestionQuery {
	efqq.order = append(efqq.order, o...)
	return efqq
}

// QueryForm chains the current query on the "form" edge.
func (efqq *EntFormQuestionQuery) QueryForm() *EntFormQuery {
	query := (&EntFormClient{config: efqq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := efqq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := efqq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entformquestion.Table, entformquestion.FieldID, selector),
			sqlgraph.To(entform.Table, entform.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entformquestion.FormTable, entformquestion.FormColumn),
		)
		fromU = sqlgraph.SetNeighbors(efqq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EntFormQuestion entity from the query.
// Returns a *NotFoundError when no EntFormQuestion was found.
func (efqq *EntFormQuestionQuery) First(ctx context.Context) (*EntFormQuestion, error) {
	nodes, err := efqq.Limit(1).All(setContextOp(ctx, efqq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entformquestion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) FirstX(ctx context.Context) *EntFormQuestion {
	node, err := efqq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntFormQuestion ID from the query.
// Returns a *NotFoundError when no EntFormQuestion ID was found.
func (efqq *EntFormQuestionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = efqq.Limit(1).IDs(setContextOp(ctx, efqq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entformquestion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) FirstIDX(ctx context.Context) int {
	id, err := efqq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntFormQuestion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntFormQuestion entity is found.
// Returns a *NotFoundError when no EntFormQuestion entities are found.
func (efqq *EntFormQuestionQuery) Only(ctx context.Context) (*EntFormQuestion, error) {
	nodes, err := efqq.Limit(2).All(setContextOp(ctx, efqq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entformquestion.Label}
	default:
		return nil, &NotSingularError{entformquestion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) OnlyX(ctx context.Context) *EntFormQuestion {
	node, err := efqq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntFormQuestion ID in the query.
// Returns a *NotSingularError when more than one EntFormQuestion ID is found.
// Returns a *NotFoundError when no entities are found.
func (efqq *EntFormQuestionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = efqq.Limit(2).IDs(setContextOp(ctx, efqq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entformquestion.Label}
	default:
		err = &NotSingularError{entformquestion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) OnlyIDX(ctx context.Context) int {
	id, err := efqq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntFormQuestions.
func (efqq *EntFormQuestionQuery) All(ctx context.Context) ([]*EntFormQuestion, error) {
	ctx = setContextOp(ctx, efqq.ctx, "All")
	if err := efqq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntFormQuestion, *EntFormQuestionQuery]()
	return withInterceptors[[]*EntFormQuestion](ctx, efqq, qr, efqq.inters)
}

// AllX is like All, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) AllX(ctx context.Context) []*EntFormQuestion {
	nodes, err := efqq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntFormQuestion IDs.
func (efqq *EntFormQuestionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if efqq.ctx.Unique == nil && efqq.path != nil {
		efqq.Unique(true)
	}
	ctx = setContextOp(ctx, efqq.ctx, "IDs")
	if err = efqq.Select(entformquestion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) IDsX(ctx context.Context) []int {
	ids, err := efqq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (efqq *EntFormQuestionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, efqq.ctx, "Count")
	if err := efqq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, efqq, querierCount[*EntFormQuestionQuery](), efqq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) CountX(ctx context.Context) int {
	count, err := efqq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (efqq *EntFormQuestionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, efqq.ctx, "Exist")
	switch _, err := efqq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (efqq *EntFormQuestionQuery) ExistX(ctx context.Context) bool {
	exist, err := efqq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntFormQuestionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (efqq *EntFormQuestionQuery) Clone() *EntFormQuestionQuery {
	if efqq == nil {
		return nil
	}
	return &EntFormQuestionQuery{
		config:     efqq.config,
		ctx:        efqq.ctx.Clone(),
		order:      append([]entformquestion.OrderOption{}, efqq.order...),
		inters:     append([]Interceptor{}, efqq.inters...),
		predicates: append([]predicate.EntFormQuestion{}, efqq.predicates...),
		withForm:   efqq.withForm.Clone(),
		// clone intermediate query.
		sql:  efqq.sql.Clone(),
		path: efqq.path,
	}
}

// WithForm tells the query-builder to eager-load the nodes that are connected to
// the "form" edge. The optional arguments are used to configure the query builder of the edge.
func (efqq *EntFormQuestionQuery) WithForm(opts ...func(*EntFormQuery)) *EntFormQuestionQuery {
	query := (&EntFormClient{config: efqq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	efqq.withForm = query
	return efqq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntFormQuestion.Query().
//		GroupBy(entformquestion.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (efqq *EntFormQuestionQuery) GroupBy(field string, fields ...string) *EntFormQuestionGroupBy {
	efqq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntFormQuestionGroupBy{build: efqq}
	grbuild.flds = &efqq.ctx.Fields
	grbuild.label = entformquestion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.EntFormQuestion.Query().
//		Select(entformquestion.FieldTitle).
//		Scan(ctx, &v)
func (efqq *EntFormQuestionQuery) Select(fields ...string) *EntFormQuestionSelect {
	efqq.ctx.Fields = append(efqq.ctx.Fields, fields...)
	sbuild := &EntFormQuestionSelect{EntFormQuestionQuery: efqq}
	sbuild.label = entformquestion.Label
	sbuild.flds, sbuild.scan = &efqq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntFormQuestionSelect configured with the given aggregations.
func (efqq *EntFormQuestionQuery) Aggregate(fns ...AggregateFunc) *EntFormQuestionSelect {
	return efqq.Select().Aggregate(fns...)
}

func (efqq *EntFormQuestionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range efqq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, efqq); err != nil {
				return err
			}
		}
	}
	for _, f := range efqq.ctx.Fields {
		if !entformquestion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if efqq.path != nil {
		prev, err := efqq.path(ctx)
		if err != nil {
			return err
		}
		efqq.sql = prev
	}
	return nil
}

func (efqq *EntFormQuestionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntFormQuestion, error) {
	var (
		nodes       = []*EntFormQuestion{}
		withFKs     = efqq.withFKs
		_spec       = efqq.querySpec()
		loadedTypes = [1]bool{
			efqq.withForm != nil,
		}
	)
	if efqq.withForm != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, entformquestion.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntFormQuestion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntFormQuestion{config: efqq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(efqq.modifiers) > 0 {
		_spec.Modifiers = efqq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, efqq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := efqq.withForm; query != nil {
		if err := efqq.loadForm(ctx, query, nodes, nil,
			func(n *EntFormQuestion, e *EntForm) { n.Edges.Form = e }); err != nil {
			return nil, err
		}
	}
	for i := range efqq.loadTotal {
		if err := efqq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (efqq *EntFormQuestionQuery) loadForm(ctx context.Context, query *EntFormQuery, nodes []*EntFormQuestion, init func(*EntFormQuestion), assign func(*EntFormQuestion, *EntForm)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EntFormQuestion)
	for i := range nodes {
		if nodes[i].ent_form_questions == nil {
			continue
		}
		fk := *nodes[i].ent_form_questions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(entform.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ent_form_questions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (efqq *EntFormQuestionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := efqq.querySpec()
	if len(efqq.modifiers) > 0 {
		_spec.Modifiers = efqq.modifiers
	}
	_spec.Node.Columns = efqq.ctx.Fields
	if len(efqq.ctx.Fields) > 0 {
		_spec.Unique = efqq.ctx.Unique != nil && *efqq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, efqq.driver, _spec)
}

func (efqq *EntFormQuestionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entformquestion.Table, entformquestion.Columns, sqlgraph.NewFieldSpec(entformquestion.FieldID, field.TypeInt))
	_spec.From = efqq.sql
	if unique := efqq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if efqq.path != nil {
		_spec.Unique = true
	}
	if fields := efqq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entformquestion.FieldID)
		for i := range fields {
			if fields[i] != entformquestion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := efqq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := efqq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := efqq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := efqq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (efqq *EntFormQuestionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(efqq.driver.Dialect())
	t1 := builder.Table(entformquestion.Table)
	columns := efqq.ctx.Fields
	if len(columns) == 0 {
		columns = entformquestion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if efqq.sql != nil {
		selector = efqq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if efqq.ctx.Unique != nil && *efqq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range efqq.predicates {
		p(selector)
	}
	for _, p := range efqq.order {
		p(selector)
	}
	if offset := efqq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := efqq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntFormQuestionGroupBy is the group-by builder for EntFormQuestion entities.
type EntFormQuestionGroupBy struct {
	selector
	build *EntFormQuestionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (efqgb *EntFormQuestionGroupBy) Aggregate(fns ...AggregateFunc) *EntFormQuestionGroupBy {
	efqgb.fns = append(efqgb.fns, fns...)
	return efqgb
}

// Scan applies the selector query and scans the result into the given value.
func (efqgb *EntFormQuestionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, efqgb.build.ctx, "GroupBy")
	if err := efqgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntFormQuestionQuery, *EntFormQuestionGroupBy](ctx, efqgb.build, efqgb, efqgb.build.inters, v)
}

func (efqgb *EntFormQuestionGroupBy) sqlScan(ctx context.Context, root *EntFormQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(efqgb.fns))
	for _, fn := range efqgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*efqgb.flds)+len(efqgb.fns))
		for _, f := range *efqgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*efqgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := efqgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntFormQuestionSelect is the builder for selecting fields of EntFormQuestion entities.
type EntFormQuestionSelect struct {
	*EntFormQuestionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (efqs *EntFormQuestionSelect) Aggregate(fns ...AggregateFunc) *EntFormQuestionSelect {
	efqs.fns = append(efqs.fns, fns...)
	return efqs
}

// Scan applies the selector query and scans the result into the given value.
func (efqs *EntFormQuestionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, efqs.ctx, "Select")
	if err := efqs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntFormQuestionQuery, *EntFormQuestionSelect](ctx, efqs.EntFormQuestionQuery, efqs, efqs.inters, v)
}

func (efqs *EntFormQuestionSelect) sqlScan(ctx context.Context, root *EntFormQuestionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(efqs.fns))
	for _, fn := range efqs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*efqs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := efqs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
