// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"ezbiz.com/ent/forminstance"
	"ezbiz.com/ent/formspec"
	"ezbiz.com/ent/predicate"
	"ezbiz.com/ent/questiongroup"
	"ezbiz.com/ent/user"
)

// FormSpecQuery is the builder for querying FormSpec entities.
type FormSpecQuery struct {
	config
	ctx                     *QueryContext
	order                   []formspec.OrderOption
	inters                  []Interceptor
	predicates              []predicate.FormSpec
	withQuestionGroups      *QuestionGroupQuery
	withFormInstances       *FormInstanceQuery
	withOwner               *UserQuery
	withFKs                 bool
	modifiers               []func(*sql.Selector)
	loadTotal               []func(context.Context, []*FormSpec) error
	withNamedQuestionGroups map[string]*QuestionGroupQuery
	withNamedFormInstances  map[string]*FormInstanceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FormSpecQuery builder.
func (fsq *FormSpecQuery) Where(ps ...predicate.FormSpec) *FormSpecQuery {
	fsq.predicates = append(fsq.predicates, ps...)
	return fsq
}

// Limit the number of records to be returned by this query.
func (fsq *FormSpecQuery) Limit(limit int) *FormSpecQuery {
	fsq.ctx.Limit = &limit
	return fsq
}

// Offset to start from.
func (fsq *FormSpecQuery) Offset(offset int) *FormSpecQuery {
	fsq.ctx.Offset = &offset
	return fsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fsq *FormSpecQuery) Unique(unique bool) *FormSpecQuery {
	fsq.ctx.Unique = &unique
	return fsq
}

// Order specifies how the records should be ordered.
func (fsq *FormSpecQuery) Order(o ...formspec.OrderOption) *FormSpecQuery {
	fsq.order = append(fsq.order, o...)
	return fsq
}

// QueryQuestionGroups chains the current query on the "question_groups" edge.
func (fsq *FormSpecQuery) QueryQuestionGroups() *QuestionGroupQuery {
	query := (&QuestionGroupClient{config: fsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(formspec.Table, formspec.FieldID, selector),
			sqlgraph.To(questiongroup.Table, questiongroup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, formspec.QuestionGroupsTable, formspec.QuestionGroupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(fsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFormInstances chains the current query on the "form_instances" edge.
func (fsq *FormSpecQuery) QueryFormInstances() *FormInstanceQuery {
	query := (&FormInstanceClient{config: fsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(formspec.Table, formspec.FieldID, selector),
			sqlgraph.To(forminstance.Table, forminstance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, formspec.FormInstancesTable, formspec.FormInstancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(fsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOwner chains the current query on the "owner" edge.
func (fsq *FormSpecQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: fsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(formspec.Table, formspec.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, formspec.OwnerTable, formspec.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(fsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FormSpec entity from the query.
// Returns a *NotFoundError when no FormSpec was found.
func (fsq *FormSpecQuery) First(ctx context.Context) (*FormSpec, error) {
	nodes, err := fsq.Limit(1).All(setContextOp(ctx, fsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{formspec.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fsq *FormSpecQuery) FirstX(ctx context.Context) *FormSpec {
	node, err := fsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FormSpec ID from the query.
// Returns a *NotFoundError when no FormSpec ID was found.
func (fsq *FormSpecQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(1).IDs(setContextOp(ctx, fsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{formspec.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fsq *FormSpecQuery) FirstIDX(ctx context.Context) int {
	id, err := fsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FormSpec entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FormSpec entity is found.
// Returns a *NotFoundError when no FormSpec entities are found.
func (fsq *FormSpecQuery) Only(ctx context.Context) (*FormSpec, error) {
	nodes, err := fsq.Limit(2).All(setContextOp(ctx, fsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{formspec.Label}
	default:
		return nil, &NotSingularError{formspec.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fsq *FormSpecQuery) OnlyX(ctx context.Context) *FormSpec {
	node, err := fsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FormSpec ID in the query.
// Returns a *NotSingularError when more than one FormSpec ID is found.
// Returns a *NotFoundError when no entities are found.
func (fsq *FormSpecQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(2).IDs(setContextOp(ctx, fsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{formspec.Label}
	default:
		err = &NotSingularError{formspec.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fsq *FormSpecQuery) OnlyIDX(ctx context.Context) int {
	id, err := fsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FormSpecs.
func (fsq *FormSpecQuery) All(ctx context.Context) ([]*FormSpec, error) {
	ctx = setContextOp(ctx, fsq.ctx, "All")
	if err := fsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FormSpec, *FormSpecQuery]()
	return withInterceptors[[]*FormSpec](ctx, fsq, qr, fsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fsq *FormSpecQuery) AllX(ctx context.Context) []*FormSpec {
	nodes, err := fsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FormSpec IDs.
func (fsq *FormSpecQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fsq.ctx.Unique == nil && fsq.path != nil {
		fsq.Unique(true)
	}
	ctx = setContextOp(ctx, fsq.ctx, "IDs")
	if err = fsq.Select(formspec.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fsq *FormSpecQuery) IDsX(ctx context.Context) []int {
	ids, err := fsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fsq *FormSpecQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Count")
	if err := fsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fsq, querierCount[*FormSpecQuery](), fsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fsq *FormSpecQuery) CountX(ctx context.Context) int {
	count, err := fsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fsq *FormSpecQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Exist")
	switch _, err := fsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fsq *FormSpecQuery) ExistX(ctx context.Context) bool {
	exist, err := fsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FormSpecQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fsq *FormSpecQuery) Clone() *FormSpecQuery {
	if fsq == nil {
		return nil
	}
	return &FormSpecQuery{
		config:             fsq.config,
		ctx:                fsq.ctx.Clone(),
		order:              append([]formspec.OrderOption{}, fsq.order...),
		inters:             append([]Interceptor{}, fsq.inters...),
		predicates:         append([]predicate.FormSpec{}, fsq.predicates...),
		withQuestionGroups: fsq.withQuestionGroups.Clone(),
		withFormInstances:  fsq.withFormInstances.Clone(),
		withOwner:          fsq.withOwner.Clone(),
		// clone intermediate query.
		sql:  fsq.sql.Clone(),
		path: fsq.path,
	}
}

// WithQuestionGroups tells the query-builder to eager-load the nodes that are connected to
// the "question_groups" edge. The optional arguments are used to configure the query builder of the edge.
func (fsq *FormSpecQuery) WithQuestionGroups(opts ...func(*QuestionGroupQuery)) *FormSpecQuery {
	query := (&QuestionGroupClient{config: fsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fsq.withQuestionGroups = query
	return fsq
}

// WithFormInstances tells the query-builder to eager-load the nodes that are connected to
// the "form_instances" edge. The optional arguments are used to configure the query builder of the edge.
func (fsq *FormSpecQuery) WithFormInstances(opts ...func(*FormInstanceQuery)) *FormSpecQuery {
	query := (&FormInstanceClient{config: fsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fsq.withFormInstances = query
	return fsq
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (fsq *FormSpecQuery) WithOwner(opts ...func(*UserQuery)) *FormSpecQuery {
	query := (&UserClient{config: fsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fsq.withOwner = query
	return fsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FormSpec.Query().
//		GroupBy(formspec.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fsq *FormSpecQuery) GroupBy(field string, fields ...string) *FormSpecGroupBy {
	fsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FormSpecGroupBy{build: fsq}
	grbuild.flds = &fsq.ctx.Fields
	grbuild.label = formspec.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.FormSpec.Query().
//		Select(formspec.FieldName).
//		Scan(ctx, &v)
func (fsq *FormSpecQuery) Select(fields ...string) *FormSpecSelect {
	fsq.ctx.Fields = append(fsq.ctx.Fields, fields...)
	sbuild := &FormSpecSelect{FormSpecQuery: fsq}
	sbuild.label = formspec.Label
	sbuild.flds, sbuild.scan = &fsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FormSpecSelect configured with the given aggregations.
func (fsq *FormSpecQuery) Aggregate(fns ...AggregateFunc) *FormSpecSelect {
	return fsq.Select().Aggregate(fns...)
}

func (fsq *FormSpecQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fsq); err != nil {
				return err
			}
		}
	}
	for _, f := range fsq.ctx.Fields {
		if !formspec.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fsq.path != nil {
		prev, err := fsq.path(ctx)
		if err != nil {
			return err
		}
		fsq.sql = prev
	}
	return nil
}

func (fsq *FormSpecQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FormSpec, error) {
	var (
		nodes       = []*FormSpec{}
		withFKs     = fsq.withFKs
		_spec       = fsq.querySpec()
		loadedTypes = [3]bool{
			fsq.withQuestionGroups != nil,
			fsq.withFormInstances != nil,
			fsq.withOwner != nil,
		}
	)
	if fsq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, formspec.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FormSpec).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FormSpec{config: fsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(fsq.modifiers) > 0 {
		_spec.Modifiers = fsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fsq.withQuestionGroups; query != nil {
		if err := fsq.loadQuestionGroups(ctx, query, nodes,
			func(n *FormSpec) { n.Edges.QuestionGroups = []*QuestionGroup{} },
			func(n *FormSpec, e *QuestionGroup) { n.Edges.QuestionGroups = append(n.Edges.QuestionGroups, e) }); err != nil {
			return nil, err
		}
	}
	if query := fsq.withFormInstances; query != nil {
		if err := fsq.loadFormInstances(ctx, query, nodes,
			func(n *FormSpec) { n.Edges.FormInstances = []*FormInstance{} },
			func(n *FormSpec, e *FormInstance) { n.Edges.FormInstances = append(n.Edges.FormInstances, e) }); err != nil {
			return nil, err
		}
	}
	if query := fsq.withOwner; query != nil {
		if err := fsq.loadOwner(ctx, query, nodes, nil,
			func(n *FormSpec, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range fsq.withNamedQuestionGroups {
		if err := fsq.loadQuestionGroups(ctx, query, nodes,
			func(n *FormSpec) { n.appendNamedQuestionGroups(name) },
			func(n *FormSpec, e *QuestionGroup) { n.appendNamedQuestionGroups(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range fsq.withNamedFormInstances {
		if err := fsq.loadFormInstances(ctx, query, nodes,
			func(n *FormSpec) { n.appendNamedFormInstances(name) },
			func(n *FormSpec, e *FormInstance) { n.appendNamedFormInstances(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range fsq.loadTotal {
		if err := fsq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fsq *FormSpecQuery) loadQuestionGroups(ctx context.Context, query *QuestionGroupQuery, nodes []*FormSpec, init func(*FormSpec), assign func(*FormSpec, *QuestionGroup)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*FormSpec)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.QuestionGroup(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(formspec.QuestionGroupsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.form_spec_question_groups
		if fk == nil {
			return fmt.Errorf(`foreign-key "form_spec_question_groups" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "form_spec_question_groups" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (fsq *FormSpecQuery) loadFormInstances(ctx context.Context, query *FormInstanceQuery, nodes []*FormSpec, init func(*FormSpec), assign func(*FormSpec, *FormInstance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*FormSpec)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FormInstance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(formspec.FormInstancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.form_spec_form_instances
		if fk == nil {
			return fmt.Errorf(`foreign-key "form_spec_form_instances" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "form_spec_form_instances" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (fsq *FormSpecQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*FormSpec, init func(*FormSpec), assign func(*FormSpec, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FormSpec)
	for i := range nodes {
		if nodes[i].user_form_specs == nil {
			continue
		}
		fk := *nodes[i].user_form_specs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_form_specs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (fsq *FormSpecQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fsq.querySpec()
	if len(fsq.modifiers) > 0 {
		_spec.Modifiers = fsq.modifiers
	}
	_spec.Node.Columns = fsq.ctx.Fields
	if len(fsq.ctx.Fields) > 0 {
		_spec.Unique = fsq.ctx.Unique != nil && *fsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fsq.driver, _spec)
}

func (fsq *FormSpecQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(formspec.Table, formspec.Columns, sqlgraph.NewFieldSpec(formspec.FieldID, field.TypeInt))
	_spec.From = fsq.sql
	if unique := fsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fsq.path != nil {
		_spec.Unique = true
	}
	if fields := fsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formspec.FieldID)
		for i := range fields {
			if fields[i] != formspec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fsq *FormSpecQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fsq.driver.Dialect())
	t1 := builder.Table(formspec.Table)
	columns := fsq.ctx.Fields
	if len(columns) == 0 {
		columns = formspec.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fsq.sql != nil {
		selector = fsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fsq.ctx.Unique != nil && *fsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fsq.predicates {
		p(selector)
	}
	for _, p := range fsq.order {
		p(selector)
	}
	if offset := fsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedQuestionGroups tells the query-builder to eager-load the nodes that are connected to the "question_groups"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (fsq *FormSpecQuery) WithNamedQuestionGroups(name string, opts ...func(*QuestionGroupQuery)) *FormSpecQuery {
	query := (&QuestionGroupClient{config: fsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if fsq.withNamedQuestionGroups == nil {
		fsq.withNamedQuestionGroups = make(map[string]*QuestionGroupQuery)
	}
	fsq.withNamedQuestionGroups[name] = query
	return fsq
}

// WithNamedFormInstances tells the query-builder to eager-load the nodes that are connected to the "form_instances"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (fsq *FormSpecQuery) WithNamedFormInstances(name string, opts ...func(*FormInstanceQuery)) *FormSpecQuery {
	query := (&FormInstanceClient{config: fsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if fsq.withNamedFormInstances == nil {
		fsq.withNamedFormInstances = make(map[string]*FormInstanceQuery)
	}
	fsq.withNamedFormInstances[name] = query
	return fsq
}

// FormSpecGroupBy is the group-by builder for FormSpec entities.
type FormSpecGroupBy struct {
	selector
	build *FormSpecQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fsgb *FormSpecGroupBy) Aggregate(fns ...AggregateFunc) *FormSpecGroupBy {
	fsgb.fns = append(fsgb.fns, fns...)
	return fsgb
}

// Scan applies the selector query and scans the result into the given value.
func (fsgb *FormSpecGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fsgb.build.ctx, "GroupBy")
	if err := fsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormSpecQuery, *FormSpecGroupBy](ctx, fsgb.build, fsgb, fsgb.build.inters, v)
}

func (fsgb *FormSpecGroupBy) sqlScan(ctx context.Context, root *FormSpecQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fsgb.fns))
	for _, fn := range fsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fsgb.flds)+len(fsgb.fns))
		for _, f := range *fsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FormSpecSelect is the builder for selecting fields of FormSpec entities.
type FormSpecSelect struct {
	*FormSpecQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fss *FormSpecSelect) Aggregate(fns ...AggregateFunc) *FormSpecSelect {
	fss.fns = append(fss.fns, fns...)
	return fss
}

// Scan applies the selector query and scans the result into the given value.
func (fss *FormSpecSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fss.ctx, "Select")
	if err := fss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FormSpecQuery, *FormSpecSelect](ctx, fss.FormSpecQuery, fss, fss.inters, v)
}

func (fss *FormSpecSelect) sqlScan(ctx context.Context, root *FormSpecQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fss.fns))
	for _, fn := range fss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
