// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"ezbiz.com/ent/predicate"
	"ezbiz.com/ent/questionresponse"
)

// QuestionResponseDelete is the builder for deleting a QuestionResponse entity.
type QuestionResponseDelete struct {
	config
	hooks    []Hook
	mutation *QuestionResponseMutation
}

// Where appends a list predicates to the QuestionResponseDelete builder.
func (qrd *QuestionResponseDelete) Where(ps ...predicate.QuestionResponse) *QuestionResponseDelete {
	qrd.mutation.Where(ps...)
	return qrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qrd *QuestionResponseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, qrd.sqlExec, qrd.mutation, qrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (qrd *QuestionResponseDelete) ExecX(ctx context.Context) int {
	n, err := qrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qrd *QuestionResponseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(questionresponse.Table, sqlgraph.NewFieldSpec(questionresponse.FieldID, field.TypeInt))
	if ps := qrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	qrd.mutation.done = true
	return affected, err
}

// QuestionResponseDeleteOne is the builder for deleting a single QuestionResponse entity.
type QuestionResponseDeleteOne struct {
	qrd *QuestionResponseDelete
}

// Where appends a list predicates to the QuestionResponseDelete builder.
func (qrdo *QuestionResponseDeleteOne) Where(ps ...predicate.QuestionResponse) *QuestionResponseDeleteOne {
	qrdo.qrd.mutation.Where(ps...)
	return qrdo
}

// Exec executes the deletion query.
func (qrdo *QuestionResponseDeleteOne) Exec(ctx context.Context) error {
	n, err := qrdo.qrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{questionresponse.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qrdo *QuestionResponseDeleteOne) ExecX(ctx context.Context) {
	if err := qrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
